# Entrypoint is also needed as image by default set `terraform` binary as an
# entrypoint.
#image:
#  name: williamyeh/ansible:ubuntu18.04
#  entrypoint:
#    - '/usr/bin/env'
#    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
#    - 'AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}'
#    - 'AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}'

# Default output file for Terraform plan
variables:
  PLAN: plan.tfplan
  JSON_PLAN_FILE: tfplan.json
  STATE_APPLY: to.tfstate
cache:
  paths:
    - .terraform

before_script:
  - shopt -s expand_aliases
  - alias convert_report="jq -r '([.resource_changes[]?.change.actions?]|flatten)|{\"create\":(map(select(.==\"create\"))|length),\"update\":(map(select(.==\"update\"))|length),\"delete\":(map(select(.==\"delete\"))|length)}'"
#  - terraform --version
#  - packer --version
#  - ansible --version
#  - terraform --version
#  - terraform init

stages:
  - validate
  - build
  - test
  - production
  - destroy

validate:
  stage: validate
  tags: 
    - local
  environment:
    name: test
  script:
    - echo $AWS_ACCESS_KEY_ID
    - echo $AWS_SECRET_ACCESS_KEY
    - echo $AWS_DEFAULT_REGION
    - echo $CI_JOB_ID
    - export
    - echo "Terraform validate"
    - terraform --version
    - packer --version
    - ansible --version
    - terraform init
    - terraform validate

plan:
  stage: build
  tags: 
    - local
  environment:
    name: test
  script:
    - echo "Building..... terraform plan"
    - terraform plan -state=$STATE -out=$PLAN
    - terraform show --json $PLAN | convert_report > $JSON_PLAN_FILE
  artifacts:
    paths:
      - $PLAN
      - $STATE
    reports:
      terraform: $JSON_PLAN_FILE

# Separate apply job for manual launching Terraform as it can be destructive
# action.

deploy:
  stage: test
  tags: 
    - local
  environment:
    name: test
  script:
#    - terraform apply -state=$STATE -input=false $PLAN -state-out=$STATE_APPLY
    - terraform apply -state-out=$STATE_APPLY -input=false $PLAN
  artifacts:
    paths:
      - $STATE_APPLY
  dependencies:
    - plan
#  only:
#    - test
#  artifacts:
#    name: state
#    paths:
#        - $STATE


apply:
  stage: production
  tags: 
    - local
  environment:
    name: production
  script:
    - echo ".....in Production"
#    - cp ./ansible.cfg /etc/ansible/
    - terraform plan -state=$STATE -out=$PLAN
    - terraform apply -input=false $PLAN -state-out=$STATE_APPLY
  artifacts:
    paths:
      - $STATE_APPLY
  dependencies:
    - plan
#    - test
  when: manual
#  only:
#    - production

# Separate destroy job for manual launching Terraform as it can be destructive
# action.
destroy:
  stage: destroy
  tags: 
    - local
  environment:
    name: production
  script:
    - terraform destroy -state=$STATE_APPLY -input=false -auto-approve #-input=false #-auto-approve
  dependencies:
    - plan
    - deploy
#    - apply
#    - test
  when: manual
  only:
    - production