---
- name: webserver configuration
  hosts: all
  become: true

  tasks:
    - name: Install Apache
      yum: name=httpd state=absent

 #   - name: Enable Apache Service on boot
 #     service: name=httpd enabled=yes state=started

#    - name: Setting up web page
#      copy:
#        src: ./index.html
#        dest: /var/www/html/index.html

    - name: fail2BAN
      yum: name= fail2ban state=latest

    - name: Install NGINX
      yum: name=nginx state=latest update_cache=true

    - name: Enable NGINX
      service: name=nginx enabled=yes state=started